version: '3.3'
services:
  web:
    image: php:apache
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    
  mysql_db:
    image: mysql:latest
    volumes:
      - ./src/databases:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=jahitin
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1'
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql_db
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql_db
      - PMA_PORT=3306